### ISSUE TITLE
Search design

### ISSUE THREAD

**Issue by SSirjes** [Voog/design-oslo#52]
...coming soon from designer

**Comment by SSirjes** [comment]
1. Search from 860px stays same like it is now. But search result header part, there should come close "X" icon, like it is here (closing mobile menu):
![screen shot 2015-11-25 at 20 53 49](https://cloud.githubusercontent.com/assets/13623224/11406575/ac1f4b26-93b6-11e5-9294-1bc96adb5098.png)
 

2. Open search until 860px:
 "Arrow up" closes search and covers menu items

![screen shot 2015-11-25 at 20 31 40](https://cloud.githubusercontent.com/assets/13623224/11405946/a3c0fde2-93b3-11e5-875f-53da08a951d1.png)

**Comment by Stopa** [comment]
Search design on mobile has been remade slightly. Not the kind that's shown in previous comments, but the changes have been coordinated with designer.
